- ros_topic_name: "thruster1"
  gz_topic_name: "/thruster1"
  ros_type_name: "std_msgs/msg/Float32"
  gz_type_name: "gz.msgs.Float"
  subscriber_queue: 10
  publisher_queue: 10
  direction: GZ_TO_ROS
- ros_topic_name: "thruster2"
  gz_topic_name: "/thruster2"
  ros_type_name: "std_msgs/msg/Float32"
  gz_type_name: "gz.msgs.Float"
  subscriber_queue: 10
  publisher_queue: 10
  direction: GZ_TO_ROS
- ros_topic_name: "thruster3"
  gz_topic_name: "/thruster3"
  ros_type_name: "std_msgs/msg/Float32"
  gz_type_name: "gz.msgs.Float"
  subscriber_queue: 10
  publisher_queue: 10
  gz_type_name: "gz.msgs.Float"
  direction: GZ_TO_ROS
- ros_topic_name: "thruster4"
  gz_topic_name: "/thruster4"
  ros_type_name: "std_msgs/msg/Float32"
  gz_type_name: "gz.msgs.Float"
  subscriber_queue: 10
  publisher_queue: 10
  gz_type_name: "gz.msgs.Float"
  direction: GZ_TO_ROS
- ros_topic_name: "thruster5"
  gz_topic_name: "/thruster5"
  ros_type_name: "std_msgs/msg/Float32"
  gz_type_name: "gz.msgs.Float"
  subscriber_queue: 10
  publisher_queue: 10
  direction: GZ_TO_ROS
- ros_topic_name: "thruster6"
  gz_topic_name: "/thruster6"
  ros_type_name: "std_msgs/msg/Float32"
  gz_type_name: "gz.msgs.Float"
  subscriber_queue: 10
  publisher_queue: 10
  direction: GZ_TO_ROS
